//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vluchtprikker.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VluchtprikkerEntities : DbContext
    {
        public VluchtprikkerEntities()
            : base("name=VluchtprikkerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Availability> Availabilities { get; set; }
        public DbSet<Comment> Comments { get; set; }
        public DbSet<EmailType> EmailTypes { get; set; }
        public DbSet<Flight> Flights { get; set; }
        public DbSet<FlightSearch> FlightSearches { get; set; }
        public DbSet<Participant> Participants { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<Route> Routes { get; set; }
        public DbSet<Station> Stations { get; set; }
        public DbSet<EventStatus> EventStatus { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Error> Errors { get; set; }
    }
}
