//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgendaAssistant.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Availability = new HashSet<Availability>();
            this.Comment = new HashSet<Comment>();
            this.Event = new HashSet<Event>();
            this.Participant = new HashSet<Participant>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string FirstNameInPassport { get; set; }
        public string LastNameInPassport { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual ICollection<Availability> Availability { get; set; }
        public virtual ICollection<Comment> Comment { get; set; }
        public virtual ICollection<Event> Event { get; set; }
        public virtual ICollection<Participant> Participant { get; set; }
    }
}
